# Welcome to Jupyter!

In [ ]:
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Tugas Event 2 - Solving Real-World Problems with Data Science\n",
    "<h2> Identitas:</h2>\n",
    "<ul>\n",
    "    <li>Nama :\n",
    "        <ul>\n",
    "            <li>Hanan Nurul Hardyana Zain</li>\n",
    "            <li>Universitas : Universitas Diponegoro</li>\n",
    "        </ul>\n",
    "    </li>\n",
    "    <li>Tanggal Mulai : 11 November 2020\n",
    "    </li>\n",
    "    <li>Sumber Dataset : Survey Gform mahasiswa jurusan Informatika Undip angkatan 2020\n",
    "    </li>\n",
    "</ul>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 1. Data Observation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Timestamp</th>\n",
       "      <th>Assalamualaikum, halo, kamu cewe apa cowo?</th>\n",
       "      <th>Nama kamu siapa? boleh nama samaran kalo malu</th>\n",
       "      <th>Seberapa penting pasangan yang sesuai dengan tipe idaman kamu?</th>\n",
       "      <th>Seberapa penting pasangan dengan keaatan yang tinggi kepada Tuhan Yang Maha Esa?</th>\n",
       "      <th>Seberapa penting pasangan yang pinter buat kamu?</th>\n",
       "      <th>Seberapa penting frekuensi komunikasi tiap waktu?</th>\n",
       "      <th>Seberapa penting hadiah dari pasangan kamu?</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>11/12/2020 23:18:02</td>\n",
       "      <td>cewe</td>\n",
       "      <td>Hanz</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>11/12/2020 23:18:18</td>\n",
       "      <td>cowo</td>\n",
       "      <td>Ucup</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
          			3	5	5	3	1
       "      <td>11/13/2020 0:06:19</td>\n",
       "      <td>cewe</td>\n",
       "      <td>Atika Resti Rahmanda</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>11/13/2020 4:38:18</td>\n",
       "      <td>cowo</td>\n",
       "      <td>Jay</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>11/13/2020 0:54:25</td>\n",
       "      <td>cowo</td>\n",
       "      <td>Wildan</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            Timestamp    Assalamualaikum, halo, kamu cewe apa cowo?  Nama kamu siapa? boleh nama samaran kalo malu  \\\n",
       "0  11/12/2020 23:18:02    cewe                                                           Hanz  \n",
       "1  11/12/2020 23:18:18    cowo                                                          Ucup   \n",
       "2  11/13/2020 0:06:19     cewe                                          Atika Resti Rahmanda   \n",
       "3  11/13/2020 4:38:18     cowo                                                           Ezr   \n",
       "4  11/13/2020 0:54:25     cowo                                                        Wildan   \n",
       "\n",
       "  Seberapa penting pasangan yang sesuai dengan tipe idaman kamu?  \\\n",
       "0                                           5   \n",
       "1                                           5   \n",
       "2                                           3   \n",
       "3                                           5   \n",
       "4                                           4   \n",
       "\n",
       "   SSeberapa penting pasangan dengan keaatan yang tinggi kepada Tuhan Yang Maha Esa?  \\\n",
       "0                                         5   \n",
       "1                                         3   \n",
       "2                                         3   \n",
       "3                                         5   \n",
       "4                                         4   \n",
       "\n",
       "   Seberapa penting pasangan yang pinter buat kamu?  \\\n",
       "0                                         5   \n",
       "1                                         5   \n",
       "2                                         5   \n",
       "3                                         5   \n",
       "4                                         4   \n",
       "\n",
       "   Seberapa penting frekuensi komunikasi tiap waktu?  \\\n",
       "0                                            5   \n",
       "1                                            4   \n",
       "2                                            3   \n",
       "3                                            5   \n",
       "4                                            4   \n",
       "\n",
       "  Seberapa penting hadiah dari pasangan kamu?  \\\n",
       "0                                                5   \n",
       "1                                                2   \n",
       "2                                                1   \n",
       "3                                                5   \n",
       "4                                                2   \n",
       "\n",
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#import library panda dan NearestNeighbors dari sklearn\n",
    "import pandas as pd\n",
    "from sklearn.neighbors import NearestNeighbors\n",
    "#membaca file csv\n",
    "df = pd.read_csv('respons2.csv')\n",
    "#menampilkan data csv (headnya saja)\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 2. Data Preparation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Assalamualaikum, halo, kamu cewe apa cowo?</th>\n",
       "      <th>Nama kamu siapa? boleh nama samaran kalo malu</th>\n",
       "      <th>Seberapa penting pasangan yang sesuai dengan tipe idaman kamu?</th>\n",
       "      <th>Seberapa penting pasangan dengan keaatan yang tinggi kepada Tuhan Yang Maha Esa?</th>\n",
       "      <th>Seberapa penting pasangan yang pinter buat kamu?</th>\n",
       "      <th>Seberapa penting frekuensi komunikasi tiap waktu?</th>\n",
       "      <th>Seberapa penting hadiah dari pasangan kamu?</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Hanz</td>\n",
       "      <td>cewe</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Ucup</td>\n",
       "      <td>cowo</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Atika Resti Rahmanda</td>\n",
       "      <td>cewe</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Ezr</td>\n",
       "      <td>cowo</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Wildan</td>\n",
       "      <td>cowo</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       Assalamualaikum, halo, kamu cewe apa cowo?	Nama kamu siapa? boleh nama samaran kalo malu \\\n",
       "0    cewe            Hanz   \n",
       "1    cowo            Ucup   \n",
       "2    cewe            Atika Resti Rahmanda   \n",
       "3    cowo            Ezr   \n",
       "4    cowo            Wildan   \n",
       "\n",
       "   Seberapa penting pasangan yang sesuai dengan tipe idaman kamu?  \\\n",
       "0                                           5   \n",
       "1                                           5   \n",
       "2                                           3   \n",
       "3                                           5   \n",
       "4                                           4   \n",
       "\n",
       "   Seberapa penting pasangan dengan keaatan yang tinggi kepada Tuhan Yang Maha Esa?  \\\n",
       "0                                         5   \n",
       "1                                         3   \n",
       "2                                         5   \n",
       "3                                         5   \n",
       "4                                         4   \n",
       "\n",
       "   Seberapa penting pasangan yang pinter buat kamu?  \\\n",
       "0                                         5   \n",
       "1                                         5   \n",
       "2                                         5   \n",
       "3                                         5   \n",
       "4                                         4   \n",
       "\n",
       "  Seberapa penting frekuensi komunikasi tiap waktu?  \\\n",
       "0                                            5   \n",
       "1                                            4   \n",
       "2                                            3   \n",
       "3                                            5   \n",
       "4                                            4   \n",
       "\n",
       "   Seberapa penting hadiah dari pasangan kamu? \\\n",
       "0                                                5   \n",
       "1                                                2   \n",
       "2                                                1   \n",
       "3                                                5   \n",
       "4                                                2"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Menghapus Kolom timestamp karena tidak dibutuhkan dan kolom komentar karena tidak punta nilai kuantitatif\n",
    "df = df.iloc[:, 1:-1]\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name</th>\n",
       "      <th>gender</th>\n",
       "      <th>physic</th>\n",
       "      <th>humor</th>\n",
       "      <th>roman</th>\n",
       "      <th>attention</th>\n",
       "      <th>logic</th>\n",
       "      <th>qt</th>\n",
       "      <th>serious</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Hanz</td>\n",
       "      <td>cewek</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Ucup</td>\n",
       "      <td>cowo</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Atika Resti Rahmada</td>\n",
       "      <td>cewe</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Ezr</td>\n",
       "      <td>cowo</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Wildan</td>\n",
       "      <td>cowo</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
          0 Hanz	cewe	5	5	5	5	5
1 Ucup  cowo	5	3	5	4	2
2 Atika Resti Rahmanda cewe	3	5	5	3	1
3 Jay cowo	5	5	5	5	5
4 Wildan cowo	4	4	4	4	2
       "     name                 gender  physic  humor  roman  attention  logic  \\\n",
       "0    Hanz                 cewe       5      5      5          5      5      \n",
       "1    Ucup                 cowo       5      3      5          4      2      \n",
       "2    Atika Resti Rahmanda cewe       4      4      3          4      5      \n",
       "3    Ezr                  cowo       5      5      5          5      5      \n",
       "4    Wildan               cowo       4      4      4          4      2      \n",
       "\n",
      ]
     },
     "execution_count": 0,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Merename kolom supaya mudah dipanggil\n",
    "df.columns = ['name', 'gender', 'physic', 'humor', 'roman', 'attention', 'logic', 'qt', 'serious']\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Mengklasifikasikan gender laki-laki dan perempuan\n",
    "df['gender'] = df['gender'].apply(lambda x:0 if x == 'Cowok' else 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "m_df = df[df['gender'] == 0]\n",
    "f_df = df[df['gender'] == 1]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h1>3. Statistik & Data Analisis</h1>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.legend.Legend at 0x2723b9beeb0>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {

This repo contains an introduction to [Jupyter](https://jupyter.org) and [IPython](https://ipython.org).

Outline of some basics:

* [Notebook Basics](../examples/Notebook/Notebook%20Basics.ipynb)
* [IPython - beyond plain python](../examples/IPython%20Kernel/Beyond%20Plain%20Python.ipynb)
* [Markdown Cells](../examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)
* [Rich Display System](../examples/IPython%20Kernel/Rich%20Output.ipynb)
* [Custom Display logic](../examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb)
* [Running a Secure Public Notebook Server](../examples/Notebook/Running%20the%20Notebook%20Server.ipynb#Securing-the-notebook-server)
* [How Jupyter works](../examples/Notebook/Multiple%20Languages%2C%20Frontends.ipynb) to run code in different languages.

You can also get this tutorial and run it on your laptop:

    git clone https://github.com/ipython/ipython-in-depth

Install IPython and Jupyter:

with [conda](https://www.anaconda.com/download):

    conda install ipython jupyter

with pip:

    # first, always upgrade pip!
    pip install --upgrade pip
    pip install --upgrade ipython jupyter

Start the notebook in the tutorial directory:

    cd ipython-in-depth
    jupyter notebook